language: node_js

node_js:
  - 'stable'

# Use container-based Travis infrastructure.
sudo: true

cache:
  directories:
    - node_modules

before_install:
  - echo "Getting $VERSION of　Chrome-stable"
  - export CHROME=google-chrome-stable_current_amd64.deb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo chmod 1777 /dev/shm
  - ls -l /usr/bin/google-chrome
  - wget https://dl.google.com/linux/direct/$CHROME
  - sudo dpkg --install $CHROME || sudo apt-get -f install
  

install:
  # Log HTTP requests
  - npm config set loglevel http
  - npm install -g npm@3.8.7
   # Instal npm dependecies and ensure that npm cache is not stale
  - npm install
   
notifications:
  email: true

 
