language: node_js
sudo: false
node_js:
  - 'stable'

cache:
  directories:
    - node_modules

before_install:
  - "nvm use $TRAVIS_NODE_VERSION"

install:
  # Install version of npm that we are locked against
  - npm install -g npm@3.8.3
  # - npm config set registry http://23.251.144.68
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  - npm --version
  # Install npm dependencies and ensure that npm cache is not stale
  - npm install

notifications:
  email: true

  after_script:
# Upload to coveralls, but don't _fail_ if coveralls is down.
  - ./node_modules/karma/bin/karma start
  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
  - node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
