language: node_js
sudo: false
node_js:
 - 'stable'
- "4"

cache:
  directories:
    - node_modules

notifications:
  email: true

before_install:
  - npm install -g npm@3.4.0
  
script:
- npm run build:dev
- npm run test

