language: node_js

node_js:
  - 'stable'

# Use container-based Travis infrastructure.
sudo: true

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      
cache:
  directories:
    - node_modules
before_script:
 - chmod +x .travis-setup
install:
  # Log HTTP requests
  - npm config set loglevel http
  - npm install -g npm@3.5.2
   # Instal npm dependecies and ensure that npm cache is not stale
  - npm install
  - ./.travis-setup.sh
  
notifications:
  email: true
