language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
  - fixtures/browser/node_modules
  - fixtures/packaging/node_modules
notifications:
  email:
    on_success: change
    on_failure: always
sudo: required
dist: trusty
addons:
  sauce_connect:
    username: "Havunen"
  jwt:
    secure: "J790OiLG2E0JJLxAJV1xCzbi3itAKsv8ee+twiEOBeL+wRexzTEN/KwfCxJzmgZBKFOREyOZNIMRhar4wpTs1y1e/bJDSNSnm0tzZrYzrRy3X/FKZSYojYHhffMskqJ3jhWhnsO2TU+O816sIBo/pQBoAiN4l09DlYVhB0h6Q2MStr4OVmJb0SZ0wjoGQjqkk1AJdSpr0D16XknDaJ0bF4Y59N5LpDMj+IQxi3BWPICilTuzvBwmbOB4mxs7fZ32mXDbPhheTJfRPunl/bGmV6kJnytflccfPXbsE5U94xVt0GIT4N0FITLrRUqFGw3IO81oFM9/L0lIbsmmp2piP2Ys0S9k/S/h/ckdzjNlYLuFrkDDBC/YAyWUz7W5QBc6JIRTI/ipzM9Tj/6Mv7016QjqjzvK3GhC00DrtMuVBUCJQAzHnm7jamI3g6clKZNitYYlTyv1/xkd7577YgSrqes0Yx6JUkHYko+lWxNyIIoQGr0BUIhjliHETqGUclDYeueap4gLsWv2SXNSRtxUWRN0bQEbiMO3bSLz36m7SmXnI4M3pqvpt6u3o0rQrKaj0u3bYXowtDw2nCkU/xhDWgMbecKVww5FlXiyB4j6Lt5rsd3tj6YYEQuqn9WMK+smjuyHkNGgkiH4uCkMhdsV7LlFHr3QPtY/pWp7oIsghDo="
  chrome: stable
  firefox: latest
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
jobs:
  include:
  - script: npm run lint
  - script:
    - npm run test:coverage
    - npm run coveralls
  - script: npm run test:browser:sauce
  - stage: Build
    script:
    - npm run build
    - npm run test:package
