language: node_js

node_js:
  - 'stable'

# Use container-based Travis infrastructure.
sudo: true

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      
cache:
  directories:
    - node_modules
before_script:
  # Setup headless X per http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - sudo apt-get update -q
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

  #- 'if [ -n "$REMOTE_ARG" ]; then (java -jar selenium-server.jar > /dev/null &); fi'
  #- 'if [ -n "$REMOTE_ARG" ]; then sleep 60; fi'
script:
  - chmod u+x ./.travis-setup.sh
  - bash -c ./.travis-setup.sh   
install:
  # Log HTTP requests
  - npm config set loglevel http
  - npm install -g npm@3.5.2
   # Instal npm dependecies and ensure that npm cache is not stale
  - npm install
notifications:
  email: true
