name: Inferno
description: > # An extremely fast, React-like JavaScript library for building modern user interfaces
url: //infernojs.github.io/docs

gems:
  - jekyll-sitemap

# Defaults
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: get-started
    type: pages
  values:
    layout: get-started
- scope:
    path: benefits
    type: pages
  values:
    layout: benefits
- scope:
    path: learning-resources
    type: pages
  values:
    layout: learning-resources

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: _sass

exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- node_modules
- README.md
