name: Inferno
description: > # An extremely fast, React-like JavaScript library for building modern user interfaces
url: http://www.infernojs.org

# Defaults
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: _sass

exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- node_modules
- README.md
