---
name: Inferno
description: A Blazing fast, React-like, javascript library for building modern user interfaces 

permalink: pretty
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
  - scope:
      path: guides
      type: pages
    values:
      layout: page
  - scope:
      path: api
      type: pages
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _examples
  - _site
  - .babelrc
  - Procfile
  - webpack.config.js
port: 8080
source: src

gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: compressed

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - footnotes

